### ISSUE TITLE
Is this still supported? Anyone have a docker container image / docker-compose for this?

### ISSUE THREAD

**Issue by vulcanjedi** [bonigarcia/dualsub#26]
My wifes was an immigrant and we used to watch stuff to learn languages. This was really helpful educational tool. One thing I discovered was some utilities that would create a merger / unifty multiple language subs and display them concurrently at the same time.
I know theres some web tools out there which as seemingly innocuous as a sub file could be....rather self host......also rather bulk / automate then ad hoc generate on demand.

**Comment by bonigarcia** [comment]
Sorry but I don't have time to maintain DualSub. Nevertheless, the current release should still work. I recommend you to download directly the executable JAR: [dualsub-1.1.0.jar](https://github.com/bonigarcia/dualsub/releases/download/v1.1.0/dualsub-1.1.0.jar) 

You will need Java installed in your machine.
