### ISSUE TITLE
Auto translation error

### ISSUE THREAD

**Issue by nskaggs** [bonigarcia/dualsub#6]
Seems google changed the URL for translation:

class java.io.IOException:Server returned HTTP response code: 503 for URL: http://ipv4.google.com/sorry/IndexRedirect?continue=http://translate.google.com/translate_a/t%3Fclient%3Dp%26text%3D%25C3%2589sta%2Bes%2Bla%2Bhistoria%2Bde%2BLola%2By%2BAna%252C%2B%26sl%3Des%26tl%3Den&q=CGMSBGx0uBgY6fyIrgUiGQDxp4NL5i4O5wE8F4dPXjZrQSYuD97wW54
    sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1839)
    sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
    com.github.dualsub.translate.Translator.connect(Translator.java:80)
    com.github.dualsub.translate.Translator.translate(Translator.java:61)
    com.github.dualsub.srt.Srt.<init>(Srt.java:67)
    com.github.dualsub.srt.Worker.doInBackground(Worker.java:128)
    com.github.dualsub.srt.Worker.doInBackground(Worker.java:37)
    javax.swing.SwingWorker$1.call(SwingWorker.java:295)
    java.util.concurrent.FutureTask.run(FutureTask.java:266)
    javax.swing.SwingWorker.run(SwingWorker.java:334)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    java.lang.Thread.run(Thread.java:745)

**Comment by bonigarcia** [comment]
Google has changed the API for Translate, and hence this feature is not working any more in release 1.0.0 of DualSub. I solved this in problem in release 1.0.1. I had to implement a little hack to read the captcha from Google Translate getting the cookie `GOOGLE_ABUSE_EXEMPTION`.

Next "official" release will be 1.1.0. So far it is not ready. In the meantime, version 1.0.1 of the executable JAR can be obtained from the source code as follows:

1. Clone/fork DualSub: `git clone https://github.com/bonigarcia/dualsub.git`
2. Checkout v1.0.1 tag: `git checkout v1.0.1`
3. Package JAR: `mvn clean compile assembly:single`
