### ISSUE TITLE
Cannot install on Manjaro Linux (Archbased):

### ISSUE THREAD

**Issue by burgerkalif** [bonigarcia/dualsub#7]
==> Entering fakeroot environment...
==> Starting package()...
install: cannot stat './target/dualsub-1.1.0-SNAPSHOT-jar-with-dependencies.jar': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
==> ERROR: Makepkg was unable to build dualsub-git.

**Comment by bonigarcia** [comment]
I am not supporting these distributions. The only official release repository is [GiHub](https://github.com/bonigarcia/dualsub/releases). Maybe in this [page](https://aur.archlinux.org/packages/dualsub-git/) you can find more info.
