### ISSUE TITLE
Questionare bugged the software

### ISSUE THREAD

**Issue by sdfgsdfgsdfgsdfsafsdfased** [bonigarcia/dualsub#9]
I completed already more than 10 times. But your forced questionnaire don't let me use the software.
Downgrading to 1.0 until you remove this nonsense.

**Comment by bonigarcia** [comment]
I have closed the form. Now the problem should be solve in version 1.1.0. Nevertheless, I'm planning to release a new version (1.2.0) solving other bugs.
